name: dnd_sholat
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: 3.1.0
  go_router: 17.0.1
  riverpod_annotation: 4.0.0
  geolocator: 14.0.2
  geocoding: 4.0.0
  timezone: 0.10.1
  flutter_timezone: 5.0.1
  adhan_dart: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: 2.10.4
  riverpod_generator: 4.0.0+1
  riverpod_lint: 3.1.0

flutter:
  uses-material-design: true
